Restaurants =
    [
    {
        "Restaurant ID": 6317637,
        "Restaurant Name": "Le Petit Souffle",
        "Country Code": 162,
        "City": "Makati City",
        "Address": "Third Floor, Century City Mall, Kalayaan Avenue, Poblacion, Makati City",
        "Locality": "Century City Mall, Poblacion, Makati City",
        "Locality Verbose": "Century City Mall, Poblacion, Makati City, Makati City",
        "Longitude": 121.027535,
        "Latitude": 14.565443,
        "Cuisines": "French, Japanese, Desserts",
        "Average Cost for two": 1100,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
            "Has Online delivery": "Yes",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 314
    },
    {
        "Restaurant ID": 6304287,
        "Restaurant Name": "Izakaya Kikufuji",
        "Country Code": 162,
        "City": "Makati City",
        "Address": "Little Tokyo, 2277 Chino Roces Avenue, Legaspi Village, Makati City",
        "Locality": "Little Tokyo, Legaspi Village, Makati City",
        "Locality Verbose": "Little Tokyo, Legaspi Village, Makati City, Makati City",
        "Longitude": 121.014101,
        "Latitude": 14.553708,
        "Cuisines": "Japanese",
        "Average Cost for two": 1200,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 591
    },
    {
        "Restaurant ID": 6300002,
        "Restaurant Name": "Heat - Edsa Shangri-La",
        "Country Code": 162,
        "City": "Mandaluyong City",
        "Address": "Edsa Shangri-La, 1 Garden Way, Ortigas, Mandaluyong City",
        "Locality": "Edsa Shangri-La, Ortigas, Mandaluyong City",
        "Locality Verbose": "Edsa Shangri-La, Ortigas, Mandaluyong City, Mandaluyong City",
        "Longitude": 121.056831,
        "Latitude": 14.581404,
        "Cuisines": "Seafood, Asian, Filipino, Indian",
        "Average Cost for two": 4000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 270
    },
    {
        "Restaurant ID": 6318506,
        "Restaurant Name": "Ooma",
        "Country Code": 162,
        "City": "Mandaluyong City",
        "Address": "Third Floor, Mega Fashion Hall, SM Megamall, Ortigas, Mandaluyong City",
        "Locality": "SM Megamall, Ortigas, Mandaluyong City",
        "Locality Verbose": "SM Megamall, Ortigas, Mandaluyong City, Mandaluyong City",
        "Longitude": 121.056475,
        "Latitude": 14.585318,
        "Cuisines": "Japanese, Sushi",
        "Average Cost for two": 1500,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 365
    },
    {
        "Restaurant ID": 6314302,
        "Restaurant Name": "Sambo Kojin",
        "Country Code": 162,
        "City": "Mandaluyong City",
        "Address": "Third Floor, Mega Atrium, SM Megamall, Ortigas, Mandaluyong City",
        "Locality": "SM Megamall, Ortigas, Mandaluyong City",
        "Locality Verbose": "SM Megamall, Ortigas, Mandaluyong City, Mandaluyong City",
        "Longitude": 121.057508,
        "Latitude": 14.58445,
        "Cuisines": "Japanese, Korean",
        "Average Cost for two": 1500,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 229
    },
    {
        "Restaurant ID": 18189371,
        "Restaurant Name": "Din Tai Fung",
        "Country Code": 162,
        "City": "Mandaluyong City",
        "Address": "Ground Floor, Mega Fashion Hall, SM Megamall, Ortigas, Mandaluyong City",
        "Locality": "SM Megamall, Ortigas, Mandaluyong City",
        "Locality Verbose": "SM Megamall, Ortigas, Mandaluyong City, Mandaluyong City",
        "Longitude": 121.056314,
        "Latitude": 14.583764,
        "Cuisines": "Chinese",
        "Average Cost for two": 1000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 336
    },
    {
        "Restaurant ID": 6300781,
        "Restaurant Name": "Buffet 101",
        "Country Code": 162,
        "City": "Pasay City",
        "Address": "Building K, SM By The Bay, Sunset Boulevard, Mall of Asia Complex (MOA), Pasay City",
        "Locality": "SM by the Bay, Mall of Asia Complex, Pasay City",
        "Locality Verbose": "SM by the Bay, Mall of Asia Complex, Pasay City, Pasay City",
        "Longitude": 120.9796667,
        "Latitude": 14.53133333,
        "Cuisines": "Asian, European",
        "Average Cost for two": 2000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 520
    },
    {
        "Restaurant ID": 6301290,
        "Restaurant Name": "Vikings",
        "Country Code": 162,
        "City": "Pasay City",
        "Address": "Building B, By The Bay, Seaside Boulevard, Mall of Asia Complex (MOA), Pasay City",
        "Locality": "SM by the Bay, Mall of Asia Complex, Pasay City",
        "Locality Verbose": "SM by the Bay, Mall of Asia Complex, Pasay City, Pasay City",
        "Longitude": 120.9793333,
        "Latitude": 14.54,
        "Cuisines": "Seafood, Filipino, Asian, European",
        "Average Cost for two": 2000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 677
    },
    {
        "Restaurant ID": 6300010,
        "Restaurant Name": "Spiral - Sofitel Philippine Plaza Manila",
        "Country Code": 162,
        "City": "Pasay City",
        "Address": "Plaza Level, Sofitel Philippine Plaza Manila, CCP Complex, Pasay City",
        "Locality": "Sofitel Philippine Plaza Manila, Pasay City",
        "Locality Verbose": "Sofitel Philippine Plaza Manila, Pasay City, Pasay City",
        "Longitude": 120.98009,
        "Latitude": 14.55299,
        "Cuisines": "European, Asian, Indian",
        "Average Cost for two": 6000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 621
    },
    {
        "Restaurant ID": 6314987,
        "Restaurant Name": "Locavore",
        "Country Code": 162,
        "City": "Pasig City",
        "Address": "Brixton Technology Center, 10 Brixton Street, Kapitolyo, Pasig City",
        "Locality": "Kapitolyo",
        "Locality Verbose": "Kapitolyo, Pasig City",
        "Longitude": 121.056532,
        "Latitude": 14.572041,
        "Cuisines": "Filipino",
        "Average Cost for two": 1100,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 532
    },
    {
        "Restaurant ID": 6309903,
        "Restaurant Name": "Silantro Fil-Mex",
        "Country Code": 162,
        "City": "Pasig City",
        "Address": "75 East Capitol Drive, Kapitolyo, Pasig City",
        "Locality": "Kapitolyo",
        "Locality Verbose": "Kapitolyo, Pasig City",
        "Longitude": 121.057916,
        "Latitude": 14.567689,
        "Cuisines": "Filipino, Mexican",
        "Average Cost for two": 800,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 1070
    },
    {
        "Restaurant ID": 6309455,
        "Restaurant Name": "Mad Mark's Creamery & Good Eats",
        "Country Code": 162,
        "City": "Pasig City",
        "Address": "23 East Capitol Drive, Kapitolyo, Pasig City",
        "Locality": "Kapitolyo",
        "Locality Verbose": "Kapitolyo, Pasig City",
        "Longitude": 121.06082,
        "Latitude": 14.570849,
        "Cuisines": "American, Ice Cream, Desserts",
        "Average Cost for two": 900,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 488
    },
    {
        "Restaurant ID": 6318433,
        "Restaurant Name": "Silantro Fil-Mex",
        "Country Code": 162,
        "City": "Quezon City",
        "Address": "Second Floor, UP Town Center, Katipunan Avenue, Diliman, Quezon City",
        "Locality": "UP Town Center, Diliman, Quezon City",
        "Locality Verbose": "UP Town Center, Diliman, Quezon City, Quezon City",
        "Longitude": 121.075419,
        "Latitude": 14.649503,
        "Cuisines": "Filipino, Mexican",
        "Average Cost for two": 800,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 294
    },
    {
        "Restaurant ID": 6310470,
        "Restaurant Name": "Guevarra's",
        "Country Code": 162,
        "City": "San Juan City",
        "Address": "387 P. Guevarra Corner Argonne Street, Addition Hills, San Juan City",
        "Locality": "Addition Hills",
        "Locality Verbose": "Addition Hills, San Juan City",
        "Longitude": 121.0335917,
        "Latitude": 14.59345,
        "Cuisines": "Filipino",
        "Average Cost for two": 1000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 458
    },
    {
        "Restaurant ID": 6314605,
        "Restaurant Name": "Sodam Korean Restaurant",
        "Country Code": 162,
        "City": "San Juan City",
        "Address": "17 J. Abad Santos Drive, Little Baguio, San Juan City",
        "Locality": "Little Baguio",
        "Locality Verbose": "Little Baguio, San Juan City",
        "Longitude": 121.03811,
        "Latitude": 14.59889,
        "Cuisines": "Korean",
        "Average Cost for two": 700,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.3,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 223
    },
    {
        "Restaurant ID": 18185059,
        "Restaurant Name": "Cafe Arabelle",
        "Country Code": 162,
        "City": "Santa Rosa",
        "Address": "Ayala Mall, Solenad, Nuvali, Santa Rosa - Tagaytay Road, Don Jose, Santa Rosa",
        "Locality": "Nuvali, Don Jose, Santa Rosa",
        "Locality Verbose": "Nuvali, Don Jose, Santa Rosa, Santa Rosa",
        "Longitude": 121.05704,
        "Latitude": 14.237082,
        "Cuisines": "Cafe, American, Italian, Filipino",
        "Average Cost for two": 800,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 3.6,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 29
    },
    {
        "Restaurant ID": 18182702,
        "Restaurant Name": "Nonna's Pasta & Pizzeria",
        "Country Code": 162,
        "City": "Santa Rosa",
        "Address": "Ground Floor, Building G, Solenad 3, Nuvali, Don Jose, Santa Rosa",
        "Locality": "Solenad 3, Don Jose, Santa Rosa",
        "Locality Verbose": "Solenad 3, Don Jose, Santa Rosa, Santa Rosa",
        "Longitude": 121.0565874,
        "Latitude": 14.23767897,
        "Cuisines": "Italian, Pizza",
        "Average Cost for two": 850,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 72
    },
    {
        "Restaurant ID": 6318213,
        "Restaurant Name": "Balay Dako",
        "Country Code": 162,
        "City": "Tagaytay City",
        "Address": "Aguinaldo Highway, Tagaytay City",
        "Locality": "Tagaytay City",
        "Locality Verbose": "Tagaytay City, Tagaytay City",
        "Longitude": 120.951589,
        "Latitude": 14.101834,
        "Cuisines": "Filipino",
        "Average Cost for two": 1200,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 211
    },
    {
        "Restaurant ID": 18255654,
        "Restaurant Name": "Hobing Korean Dessert Cafe",
        "Country Code": 162,
        "City": "Taguig City",
        "Address": "Third Floor, BGC Stopover Pavillion, Rizal Drive Corner 31st Street, Bonifacio Global City, Taguig City",
        "Locality": "BGC Stopover Pavillion, Bonifacio Global City",
        "Locality Verbose": "BGC Stopover Pavillion, Bonifacio Global City, Taguig City",
        "Longitude": 121.045878,
        "Latitude": 14.55436,
        "Cuisines": "Cafe, Korean, Desserts",
        "Average Cost for two": 600,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 118
    },
    {
        "Restaurant ID": 6308205,
        "Restaurant Name": "Wildflour Cafe + Bakery",
        "Country Code": 162,
        "City": "Taguig City",
        "Address": "Ground Floor, Netlima Building, 4th Avenue Corner 26th Street, Bonifacio Global City, Taguig City",
        "Locality": "Bonifacio Global City",
        "Locality Verbose": "Bonifacio Global City, Taguig City",
        "Longitude": 121.04622,
        "Latitude": 14.549337,
        "Cuisines": "Cafe, Bakery, American, Italian",
        "Average Cost for two": 1500,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 392
    },
    {
        "Restaurant ID": 6315438,
        "Restaurant Name": "NIU by Vikings",
        "Country Code": 162,
        "City": "Taguig City",
        "Address": "Sixth Floor, SM Aura Premier, C5 Road Corner 26th Street, Bonifacio Global City, Taguig City",
        "Locality": "SM Aura Premier, Bonifacio Global City, Taguig City",
        "Locality Verbose": "SM Aura Premier, Bonifacio Global City, Taguig City, Taguig City",
        "Longitude": 121.053725,
        "Latitude": 14.545858,
        "Cuisines": "Seafood, American, Mediterranean, Japanese",
        "Average Cost for two": 3000,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.7,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 535
    },
    {
        "Restaurant ID": 6310406,
        "Restaurant Name": "The Food Hall by Todd English",
        "Country Code": 162,
        "City": "Taguig City",
        "Address": "Fifth Floor, SM Aura Premier, C5 Corner 26th Street, Bonifacio Global City, Taguig City",
        "Locality": "SM Aura Premier, Bonifacio Global City, Taguig City",
        "Locality Verbose": "SM Aura Premier, Bonifacio Global City, Taguig City, Taguig City",
        "Longitude": 121.0534998,
        "Latitude": 14.54565535,
        "Cuisines": "American, Asian, Italian, Seafood",
        "Average Cost for two": 1800,
        "Currency": "Botswana Pula(P)",
        "Has Table booking": "Yes",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 618
    },
    {
        "Restaurant ID": 6600681,
        "Restaurant Name": "Chez Michou",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCLN, 208, Bloco A, Loja 30, Asa Norte, Bras�_lia",
        "Locality": "Asa Norte",
        "Locality Verbose": "Asa Norte, Bras�_lia",
        "Longitude": -47.88178889,
        "Latitude": -15.76414167,
        "Cuisines": "Fast Food, French",
        "Average Cost for two": 55,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 3,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 6
    },
    {
        "Restaurant ID": 6601005,
        "Restaurant Name": "Caf�� Daniel Briand",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCLN 104, Bloco A, Loja 26, Asa Norte, Bras�_lia",
        "Locality": "Asa Norte",
        "Locality Verbose": "Asa Norte, Bras�_lia",
        "Longitude": -47.88266667,
        "Latitude": -15.7775,
        "Cuisines": "Cafe",
        "Average Cost for two": 30,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 1,
        "Aggregate rating": 3.8,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 9
    },
    {
        "Restaurant ID": 6600292,
        "Restaurant Name": "Casa do Biscoito Mineiro",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCLN 210, Bloco D, Loja 36/48, Asa Norte, Bras�_lia",
        "Locality": "Asa Norte",
        "Locality Verbose": "Asa Norte, Bras�_lia",
        "Longitude": -47.88213611,
        "Latitude": -15.75747222,
        "Cuisines": "Bakery",
        "Average Cost for two": 45,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 3.7,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 11
    },
    {
        "Restaurant ID": 6600441,
        "Restaurant Name": "Maori",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "CLN 110, Bloco D, Loja 28, Asa Norte, Bras�_lia",
        "Locality": "Asa Norte",
        "Locality Verbose": "Asa Norte, Bras�_lia",
        "Longitude": -47.88816667,
        "Latitude": -15.75883333,
        "Cuisines": "Brazilian",
        "Average Cost for two": 60,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 3.8,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 11
    },
    {
        "Restaurant ID": 6600970,
        "Restaurant Name": "Pizza �� Bessa",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCS 214, Bloco C, Loja 40, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.91566667,
        "Latitude": -15.83116667,
        "Cuisines": "Pizza",
        "Average Cost for two": 50,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 3.2,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 11
    },
    {
        "Restaurant ID": 6600379,
        "Restaurant Name": "Sushi Loko",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCS 213, Bloco C, Loja 35, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.91566667,
        "Latitude": -15.831,
        "Cuisines": "Japanese",
        "Average Cost for two": 80,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 3.1,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 10
    },
    {
        "Restaurant ID": 6600214,
        "Restaurant Name": "Beirute",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "CLS 109, Bloco A, Loja 2/6, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.9075,
        "Latitude": -15.82,
        "Cuisines": "Arabian",
        "Average Cost for two": 90,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 3.7,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 8
    },
    {
        "Restaurant ID": 6601218,
        "Restaurant Name": "New Koto",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCS 212, Bloco B, Loja 26, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.91016667,
        "Latitude": -15.82733333,
        "Cuisines": "Japanese",
        "Average Cost for two": 200,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 3.7,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 5
    },
    {
        "Restaurant ID": 6600060,
        "Restaurant Name": "Sandubas Caf��",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Edif�_cio Jos�� Severo, SCS 6, Bloco A, Loja 99, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.89016667,
        "Latitude": -15.797,
        "Cuisines": "Brazilian, Cafe",
        "Average Cost for two": 30,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 1,
        "Aggregate rating": 0,
        "Rating color": "White",
        "Rating text": "Not rated",
        "Votes": 2
    },
    {
        "Restaurant ID": 6600083,
        "Restaurant Name": "Villa Tevere",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "CLS 115, Bloco A, Loja 2, Asa Sul, Bras�_lia",
        "Locality": "Asa Sul",
        "Locality Verbose": "Asa Sul, Bras�_lia",
        "Longitude": -47.92366667,
        "Latitude": -15.83133333,
        "Cuisines": "Italian",
        "Average Cost for two": 150,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.1,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 12
    },
    {
        "Restaurant ID": 6601515,
        "Restaurant Name": "Rovereto",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Rua 13 Norte, Lote 4, �guas Claras, Bras�_lia",
        "Locality": "�guas Claras",
        "Locality Verbose": "�guas Claras, Bras�_lia",
        "Longitude": -48.019,
        "Latitude": -15.83716667,
        "Cuisines": "Pizza",
        "Average Cost for two": 100,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 3.1,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 9
    },
    {
        "Restaurant ID": 6601361,
        "Restaurant Name": "Buena Carne",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Avenida Arauc��rias, 1325, Loja 19, �guas Claras, Bras�_lia",
        "Locality": "�guas Claras",
        "Locality Verbose": "�guas Claras, Bras�_lia",
        "Longitude": -48.01909167,
        "Latitude": -15.839775,
        "Cuisines": "Bar Food, Brazilian",
        "Average Cost for two": 60,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 3.6,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 9
    },
    {
        "Restaurant ID": 6601602,
        "Restaurant Name": "Taco Pep",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Vila Malls, Avenida das Castanheiras, Lote 1060, �guas Claras, Bras�_lia",
        "Locality": "�guas Claras",
        "Locality Verbose": "�guas Claras, Bras�_lia",
        "Longitude": -48.01666667,
        "Latitude": -15.83483333,
        "Cuisines": "Mexican, Grill",
        "Average Cost for two": 100,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.3,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 29
    },
    {
        "Restaurant ID": 6601589,
        "Restaurant Name": "Coco Bambu",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Bras�_lia Shopping - Piso 2, SCN 5, Bloco A, Asa Norte, Bras�_lia",
        "Locality": "Bras�_lia Shopping, Asa Norte",
        "Locality Verbose": "Bras�_lia Shopping, Asa Norte, Bras�_lia",
        "Longitude": -47.889,
        "Latitude": -15.7865,
        "Cuisines": "International",
        "Average Cost for two": 230,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 17
    },
    {
        "Restaurant ID": 6601862,
        "Restaurant Name": "Tayp��",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Fashion Park, Shis Ql 17, Bloco G, Loja 208, Lago Sul, Bras�_lia",
        "Locality": "Lago Sul",
        "Locality Verbose": "Lago Sul, Bras�_lia",
        "Longitude": -47.872359,
        "Latitude": -15.860621,
        "Cuisines": "Peruvian, Latin American",
        "Average Cost for two": 100,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 3.6,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 5
    },
    {
        "Restaurant ID": 6601595,
        "Restaurant Name": "Outback Steakhouse",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "ParkShopping - Piso 2, SAI/SO, �rea 6580, Guar�� I, Bras�_lia",
        "Locality": "ParkShopping, Guar�� I",
        "Locality Verbose": "ParkShopping, Guar�� I, Bras�_lia",
        "Longitude": -47.95628333,
        "Latitude": -15.83451389,
        "Cuisines": "American, Grill",
        "Average Cost for two": 150,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 10
    },
    {
        "Restaurant ID": 6601158,
        "Restaurant Name": "Manzu��",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Pont��o Lago Sul, SHIS 10, Lote 9, Lago Sul, Bras�_lia",
        "Locality": "Pont��o Lago Sul, Lago Sul",
        "Locality Verbose": "Pont��o Lago Sul, Lago Sul, Bras�_lia",
        "Longitude": -47.87283333,
        "Latitude": -15.82566667,
        "Cuisines": "Seafood",
        "Average Cost for two": 240,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 3.2,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 6
    },
    {
        "Restaurant ID": 6600427,
        "Restaurant Name": "Coco Bambu",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "SCES, Trecho 2, Conjunto 13/36, Setor de Clubes Esportivos Sul, Bras�_lia",
        "Locality": "Setor De Clubes Esportivos Sul",
        "Locality Verbose": "Setor De Clubes Esportivos Sul, Bras�_lia",
        "Longitude": -47.8685,
        "Latitude": -15.819,
        "Cuisines": "International",
        "Average Cost for two": 230,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 30
    },
    {
        "Restaurant ID": 6600116,
        "Restaurant Name": "Gero",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "Shopping Iguatemi - piso 1, SHIN CA 4, Lote A, Lago Norte, Bras�_lia",
        "Locality": "Shopping Iguatemi, Lago Norte",
        "Locality Verbose": "Shopping Iguatemi, Lago Norte, Bras�_lia",
        "Longitude": -47.885812,
        "Latitude": -15.720118,
        "Cuisines": "Italian",
        "Average Cost for two": 350,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 3.3,
        "Rating color": "Orange",
        "Rating text": "Average",
        "Votes": 8
    },
    {
        "Restaurant ID": 6601457,
        "Restaurant Name": "Brazilian American Burgers",
        "Country Code": 30,
        "City": "Bras�_lia",
        "Address": "CLSN 301, Bloco C, Loja 86, Sudoeste, Bras�_lia",
        "Locality": "Sudoeste",
        "Locality Verbose": "Sudoeste, Bras�_lia",
        "Longitude": -47.92102778,
        "Latitude": -15.79753056,
        "Cuisines": "American, Burger",
        "Average Cost for two": 50,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 3.6,
        "Rating color": "Yellow",
        "Rating text": "Good",
        "Votes": 9
    },
    {
        "Restaurant ID": 7303219,
        "Restaurant Name": "Pesqueiro Eco Gourmet",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Praia da Barra da Tijuca, Avenida L�_cio Costa, Ilha 25, Barra da Tijuca, Rio de Janeiro",
        "Locality": "Barra da Tijuca",
        "Locality Verbose": "Barra da Tijuca, Rio de Janeiro",
        "Longitude": -43.377,
        "Latitude": -23.0115,
        "Cuisines": "Seafood, Bar Food, Brazilian",
        "Average Cost for two": 140,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 7
    },
    {
        "Restaurant ID": 7304307,
        "Restaurant Name": "Confeitaria Colombo",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Gon�_alves Dias, 32, Centro, Rio de Janeiro",
        "Locality": "Centro",
        "Locality Verbose": "Centro, Rio de Janeiro",
        "Longitude": -43.178826,
        "Latitude": -22.905293,
        "Cuisines": "Desserts, Cafe",
        "Average Cost for two": 100,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 29
    },
    {
        "Restaurant ID": 7301215,
        "Restaurant Name": "Bibi",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Santa Clara, 36, Copabana, Rio de Janeiro",
        "Locality": "Copacabana",
        "Locality Verbose": "Copacabana, Rio de Janeiro",
        "Longitude": -43.18669167,
        "Latitude": -22.97207222,
        "Cuisines": "Juices, Healthy Food",
        "Average Cost for two": 60,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.7,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 24
    },
    {
        "Restaurant ID": 7300596,
        "Restaurant Name": "Cervantes",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Avenida Prado Junior, 335 B, Copacabana, Rio de Janeiro",
        "Locality": "Copacabana",
        "Locality Verbose": "Copacabana, Rio de Janeiro",
        "Longitude": -43.17583333,
        "Latitude": -22.96216667,
        "Cuisines": "Beverages, Bar Food, Fast Food",
        "Average Cost for two": 90,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 29
    },
    {
        "Restaurant ID": 7300612,
        "Restaurant Name": "Amir",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Ronald de Carvalho, 55, Copacabana, Rio de Janeiro",
        "Locality": "Copacabana",
        "Locality Verbose": "Copacabana, Rio de Janeiro",
        "Longitude": -43.176,
        "Latitude": -22.96516667,
        "Cuisines": "Lebanese",
        "Average Cost for two": 170,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 11
    },
    {
        "Restaurant ID": 7300704,
        "Restaurant Name": "TT Burger",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Galeria River, Rua Francisco Otaviano, 67, Copacabana, Rio de Janeiro",
        "Locality": "Galeria River, Copacabana",
        "Locality Verbose": "Galeria River, Copacabana, Rio de Janeiro",
        "Longitude": -43.191,
        "Latitude": -22.98683333,
        "Cuisines": "Burger",
        "Average Cost for two": 60,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.8,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 19
    },
    {
        "Restaurant ID": 7300955,
        "Restaurant Name": "Braseiro da G��vea",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Pra�_a Santos Dumont, 116, G��vea, Rio de Janeiro",
        "Locality": "G��vea",
        "Locality Verbose": "G��vea, Rio de Janeiro",
        "Longitude": -43.227042,
        "Latitude": -22.973507,
        "Cuisines": "Brazilian, Bar Food",
        "Average Cost for two": 100,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 40
    },
    {
        "Restaurant ID": 7300521,
        "Restaurant Name": "Balada Mix",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua An�_bal de Mendon�_a, 37, Ipanema, Rio de Janeiro",
        "Locality": "Ipanema",
        "Locality Verbose": "Ipanema, Rio de Janeiro",
        "Longitude": -43.211425,
        "Latitude": -22.98520833,
        "Cuisines": "Brazilian, Healthy Food, Juices, Pizza",
        "Average Cost for two": 90,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.6,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 21
    },
    {
        "Restaurant ID": 7300515,
        "Restaurant Name": "Garota de Ipanema",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Vinicius de Moraes, 49, Ipanema, Rio de Janeiro",
        "Locality": "Ipanema",
        "Locality Verbose": "Ipanema, Rio de Janeiro",
        "Longitude": -43.203,
        "Latitude": -22.98533333,
        "Cuisines": "Brazilian, Bar Food",
        "Average Cost for two": 120,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.9,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 49
    },
    {
        "Restaurant ID": 7300483,
        "Restaurant Name": "Zaz�� Bistr�� Tropical",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Joana Ang��lica, 40, Ipanema, Rio de Janeiro",
        "Locality": "Ipanema",
        "Locality Verbose": "Ipanema, Rio de Janeiro",
        "Longitude": -43.20520833,
        "Latitude": -22.98531944,
        "Cuisines": "Brazilian",
        "Average Cost for two": 170,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.6,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 21
    },
    {
        "Restaurant ID": 7301064,
        "Restaurant Name": "Fil�� de Ouro",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Jardim Bot��nico, 731, Jardim Bot��nico, Lagoa, Rio de Janeiro",
        "Locality": "Lagoa",
        "Locality Verbose": "Lagoa, Rio de Janeiro",
        "Longitude": -43.219563,
        "Latitude": -22.966647,
        "Cuisines": "Brazilian",
        "Average Cost for two": 90,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.3,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 14
    },
    {
        "Restaurant ID": 7304312,
        "Restaurant Name": "D.O.C Ristorante",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Le Monde, Bloco 3, Lojas A/B, Avenida das Am��ricas, 3500, Barra da Tijuca, Rio de Janeiro",
        "Locality": "Le Monde, Barra da Tijuca",
        "Locality Verbose": "Le Monde, Barra da Tijuca, Rio de Janeiro",
        "Longitude": -43.34879167,
        "Latitude": -22.99991111,
        "Cuisines": "Italian",
        "Average Cost for two": 150,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 5
    },
    {
        "Restaurant ID": 7300004,
        "Restaurant Name": "Sushi Leblon",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Dias Ferreira, 256, Leblon, Rio de Janeiro",
        "Locality": "Leblon",
        "Locality Verbose": "Leblon, Rio de Janeiro",
        "Longitude": -43.227,
        "Latitude": -22.98416667,
        "Cuisines": "Japanese",
        "Average Cost for two": 250,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.6,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 25
    },
    {
        "Restaurant ID": 7300868,
        "Restaurant Name": "Talho Capixaba",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Avenida Ataulfo de Paiva, 1022, Lojas A e B, Leblon, Rio de Janeiro",
        "Locality": "Leblon",
        "Locality Verbose": "Leblon, Rio de Janeiro",
        "Longitude": -43.22566667,
        "Latitude": -22.98516667,
        "Cuisines": "Bakery, Sandwich, Brazilian",
        "Average Cost for two": 120,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.4,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 13
    },
    {
        "Restaurant ID": 7302637,
        "Restaurant Name": "Leme Light",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Gustavo Sampaio, 798, Leme, Rio de Janeiro",
        "Locality": "Leme",
        "Locality Verbose": "Leme, Rio de Janeiro",
        "Longitude": -43.17279167,
        "Latitude": -22.963925,
        "Cuisines": "Brazilian",
        "Average Cost for two": 40,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 2,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 7
    },
    {
        "Restaurant ID": 7302140,
        "Restaurant Name": "Shirley",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Gustavo Sampaio, 610, Leme, Rio de Janeiro",
        "Locality": "Leme",
        "Locality Verbose": "Leme, Rio de Janeiro",
        "Longitude": -43.17126389,
        "Latitude": -22.96337222,
        "Cuisines": "Brazilian, Seafood",
        "Average Cost for two": 250,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.2,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 8
    },
    {
        "Restaurant ID": 7305048,
        "Restaurant Name": "Quiosque Chopp Brahma",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Madureira Shopping - Loja 289/290, Piso 2, Estrada do Portela, 222, Madureira, Rio de Janeiro, RJ",
        "Locality": "Madureira",
        "Locality Verbose": "Madureira, Rio de Janeiro",
        "Longitude": -43.341164,
        "Latitude": -22.870413,
        "Cuisines": "Bar Food, Brazilian",
        "Average Cost for two": 70,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 0,
        "Rating color": "White",
        "Rating text": "Not rated",
        "Votes": 1
    },
    {
        "Restaurant ID": 7302898,
        "Restaurant Name": "Apraz�_vel",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Apraz�_vel, 62, Santa Teresa, Rio de Janeiro",
        "Locality": "Santa Teresa",
        "Locality Verbose": "Santa Teresa, Rio de Janeiro",
        "Longitude": -43.18736944,
        "Latitude": -22.92481389,
        "Cuisines": "Brazilian",
        "Average Cost for two": 300,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.7,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 44
    },
    {
        "Restaurant ID": 7302859,
        "Restaurant Name": "Aconchego Carioca",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Rua Bar��o de Iguatemi, 379, Tijuca, Rio de Janeiro",
        "Locality": "Tijuca",
        "Locality Verbose": "Tijuca, Rio de Janeiro",
        "Longitude": -43.21551111,
        "Latitude": -22.91370833,
        "Cuisines": "Brazilian, Bar Food",
        "Average Cost for two": 85,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.6,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
        "Votes": 24
    },
    {
        "Restaurant ID": 7301700,
        "Restaurant Name": "Garota de Ipanema",
        "Country Code": 30,
        "City": "Rio de Janeiro",
        "Address": "Avenida Jo��o Alves, 56, Urca, Rio de Janeiro",
        "Locality": "Urca",
        "Locality Verbose": "Urca, Rio de Janeiro",
        "Longitude": -43.16266667,
        "Latitude": -22.94783333,
        "Cuisines": "Brazilian, Bar Food",
        "Average Cost for two": 80,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 3,
        "Aggregate rating": 4.3,
        "Rating color": "Green",
        "Rating text": "Very Good",
        "Votes": 10
    },
    {
        "Restaurant ID": 6706313,
        "Restaurant Name": "Cantina Famiglia Mancini",
        "Country Code": 30,
        "City": "S��o Paulo",
        "Address": "Rua Avanhandava, 81, Bela Vista, S��o Paulo 10000",
        "Locality": "Bela Vista, Centro",
        "Locality Verbose": "Bela Vista, Centro, S��o Paulo",
        "Longitude": -46.64516667,
        "Latitude": -23.55066667,
        "Cuisines": "Italian, Pizza",
        "Average Cost for two": 250,
        "Currency": "Brazilian Real(R$)",
        "Has Table booking": "No",
        "Has Online delivery": "No",
        "Is delivering now": "No",
        "Switch to order menu": "No",
        "Price range": 4,
        "Aggregate rating": 4.5,
        "Rating color": "Dark Green",
        "Rating text": "Excellent",
     "Votes": 49
    }
]
    
